src/MeetingBundle/Entity/Meeting.php
<?php
namespace MeetingBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @ORM\Entity
 * @ORM\Entity(repositoryClass="MeetingBundle\Repository\MeetingRepository")
 * @ORM\Table(name="meetings")
 * @ORM\HasLifecycleCallbacks
 */
class Meeting
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank(message="Поле не должно быть пустым")
     * @Assert\Length(
     *      min = 10,
     *      max = 50,
     *      minMessage = "Название встречи должно быть длинее 10 символов",
     *      maxMessage = "Название встречи должно быть не более 50 символов"
     * )
     */
    protected $title;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $imgPreview;
    /**
     * @ORM\Column(type="string", nullable=true)
     */
    protected $imgFull;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $updated;

    /**
     * @ORM\Column(type="datetime")
     */
    protected $meetingDate;

    /**
     * @ORM\Column(type="string")
     */
    protected $shortDescription;
    /**
     * @Assert\NotBlank(message="Поле не должно быть пустым")
     * @ORM\Column(type="string")
     */
    protected $description;
    /**
     * @Assert\NotBlank(message="Поле не должно быть пустым")
     * @ORM\Column(type="string")
     */
    protected $venue;

    /**
     * @Assert\NotBlank(message="Поле не должно быть пустым")
     * @ORM\Column(type="integer")
     */
    protected $quantity;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="meetings")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    protected $user;

    /**
     * @ORM\ManyToMany(targetEntity="User")
     * @ORM\JoinTable(name="members",
     *      joinColumns={@ORM\JoinColumn(name="meeting_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="user_id", referencedColumnName="id")}
     *      )
     **/
    protected $members;

    /**
     * @Assert\File(maxSize="6000000")
     */
    private $previewFile;

    private $previewTemp;

    /**
     * @Assert\File(maxSize="6000000")
     */
    private $fullFile;

    private $fullTemp;

    public function __construct()
    {
        $this->members = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */

    public function getId()
    {
        return $this->id;
    }

    public function setPreviewFile(UploadedFile $file = null)
    {
        $this->previewFile = $file;
        // check if we have an old image path

        if (isset($this->imgPreview) && $this->imgPreview !== null) {
            // store the old name to delete after the update
            $this->previewTemp = $this->imgPreview;
            $this->imgPreview = null;
        } else {
            $this->imgPreview = 'initial';
        }
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getPreviewFile()
    {
        return $this->previewFile;
    }
    public function setFullFile(UploadedFile $file = null)
    {
        $this->fullFile = $file;
        // check if we have an old image path

        if (isset($this->imgFull) && $this->imgFull !== null) {
            // store the old name to delete after the update
            $this->fullTemp = $this->imgFull;
            $this->imgFull = null;
        } else {
            $this->imgFull = 'initial';
        }
    }

    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFullFile()
    {
        return $this->fullFile;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Meeting
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set imgPreview
     *
     * @param string $imgPreview
     * @return Meeting
     */
    public function setImgPreview($imgPreview)
    {
        $this->imgPreview = $imgPreview;

        return $this;
    }

    /**
     * Get imgPreview
     *
     * @return string 
     */
    public function getImgPreview()
    {
        return $this->imgPreview;
    }

    /**
     * Set imgFull
     *
     * @param string $imgFull
     * @return Meeting
     */
    public function setImgFull($imgFull)
    {
        $this->imgFull = $imgFull;

        return $this;
    }

    /**
     * Get imgFull
     *
     * @return string 
     */
    public function getImgFull()
    {
        return $this->imgFull;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Meeting
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set meetingDate
     *
     * @param \DateTime $meetingDate
     * @return Meeting
     */
    public function setMeetingDate($meetingDate)
    {
        $this->meetingDate = $meetingDate;

        return $this;
    }

    /**
     * Get meetingDate
     *
     * @return \DateTime 
     */
    public function getMeetingDate()
    {
        return $this->meetingDate;
    }

    /**
     * Set shortDescription
     *
     * @param string $shortDescription
     * @return Meeting
     */
    public function setShortDescription($shortDescription)
    {
        $this->shortDescription = $shortDescription;

        return $this;
    }

    /**
     * Get shortDescription
     *
     * @return string 
     */
    public function getShortDescription()
    {
        return $this->shortDescription;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Meeting
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set venue
     *
     * @param string $venue
     * @return Meeting
     */
    public function setVenue($venue)
    {
        $this->venue = $venue;

        return $this;
    }

    /**
     * Get venue
     *
     * @return string 
     */
    public function getVenue()
    {
        return $this->venue;
    }

    /**
     * Set quantity
     *
     * @param integer $quantity
     * @return Meeting
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * Get quantity
     *
     * @return integer 
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Set user
     *
     * @param \MeetingBundle\Entity\User $user
     * @return Meeting
     */
    public function setUser(\MeetingBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \MeetingBundle\Entity\User 
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Add members
     *
     * @param \MeetingBundle\Entity\User $members
     * @return Meeting
     */
    public function addMember(\MeetingBundle\Entity\User $members)
    {
        $this->members[] = $members;

        return $this;

    }

    /**
     * Remove members
     *
     * @param \MeetingBundle\Entity\User $members
     */
    public function removeMember(\MeetingBundle\Entity\User $members)
    {
        $this->members->removeElement($members);
    }

    /**
     * Get members
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getMembers()
    {
        return $this->members;
    }
    public function getPreviewPath()
    {
        return null === $this->imgPreview
            ? null
            : $this->getUploadRootDir().'/thumbnail/'.$this->imgPreview;
    }
    public function getFullPath()
    {
        return null === $this->imgFull
            ? null
            : $this->getUploadRootDir().'/fullImages/'.$this->imgFull;
    }

    public function getPathPreviewImg()
    {
        return null === $this->imgPreview
            ? null
            : $this->getUploadDir().'/thumbnail/'.$this->imgPreview;
    }

    public function getPathFullImg()
    {
        return null === $this->imgFull
            ? null
            : $this->getUploadDir().'/fullImages/'.$this->imgFull;
    }

    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../web'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return '/uploads';
    }
    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
    if (null !== $this->getPreviewFile()) {
            $this->getPreviewFile()->move($this->getUploadRootDir().'/thumbnail', $this->imgPreview);
            if (isset($this->previewTemp)) {
                unlink($this->getUploadRootDir().'/thumbnail/'.$this->previewTemp);
                $this->previewTemp = null;
            }
            $this->previewFile = null;
        }

     if (null !== $this->getFullFile()) {

src/MeetingBundle/Form/MeetingType.php
<?php

namespace MeetingBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class MeetingType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', 'text', array(
                'label' => "Название встречи",
                'required' => false
            ))
            ->add('venue', 'text', array(
                'label' => "Место встречи"
            ))
            ->add('previewFile', 'file', array(
                'label' => "Миниатюра",
                'required' => false
            ))
            ->add('fullFile', 'file', array(
                'label' => "Изображение",
                'required' => false
            ))
            ->add('meetingDate', 'datetime', array(
                'label' => "Дата проведения",
                'date_widget' => 'single_text',
                'time_widget' => 'choice'
            ))
            ->add('description', 'textarea', array(
                'label' => "Описание"
            ))

            ->add('shortDescription', 'textarea', array(
                'label' => "Короткое описание"
            ))
            ->add('quantity', 'integer', array(
                'label' => "Количество учасников"
            ))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'MeetingBundle\Entity\Meeting'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'meeting';
    }
}

src/MeetingBundle/Controller/MeetingController.php
<?php

namespace MeetingBundle\Controller;

use MeetingBundle\Entity\Meeting;
use MeetingBundle\Form\MeetingType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/admin")
 */
class MeetingController extends Controller
{
    /**
     * @Route("/meetings", name="admin_meetings")
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $meetings = $em->getRepository('MeetingBundle:Meeting')->findAll();
        return $this->render('MeetingBundle:Meeting:index.html.twig', array('meetings' => $meetings));
    }
    /**
     * @Route("/edit/meeting/{id}", name="admin_meeting_edit")
     */
    public function editAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $meeting = $em->getRepository('MeetingBundle:Meeting')->findOneById($id);
        $form = $this->createForm(new MeetingType(), $meeting, array(
            'action' => $this->generateUrl('admin_meeting_edit', array('id' => $meeting->getId())),
            'method' => 'POST',
        ));
        $form->add('submit', 'submit', array('label' => 'Update', 'attr' => array('class' => 'btn btn-success')));
        if ($request->getMethod() === "POST"){
            $form->handleRequest($request);
            if ($form->isValid()) {
                $em->flush();
                $this->addFlash("success", "Данные успешно обновлены!!!");
                return $this->redirect($this->generateUrl('admin_meeting_edit', array('id' => $meeting->getId())));
            }
        }

        return $this->render('MeetingBundle:Meeting:edit.html.twig', array(
            'meeting' => $meeting,
            'form'    => $form->createView()
        ));
    }
    /**
     * @Route("/new/meeting", name="admin_meeting_new")
     */
    public function newAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $meeting = new Meeting();
        $form = $this->createForm(new MeetingType(), $meeting, array(
            'action' => $this->generateUrl('admin_meeting_new'),
            'method' => 'POST',
        ));
        $form->add('submit', 'submit', array('label' => 'Create', 'attr' => array('class' => 'btn btn-success')));

        if ($request->getMethod() === "POST"){
            $form->handleRequest($request);
            if ($form->isValid()) {
                $em->persist($meeting);
                $em->flush();
                $this->addFlash("success", "Данные успешно сохранены!!!");
                return $this->redirect($this->generateUrl('admin_meeting_edit', array('id' => $meeting->getId())));
            }
        }

        return $this->render('MeetingBundle:Meeting:new.html.twig', array(
            'meeting' => $meeting,
            'form'    => $form->createView()
        ));
    }
     /**
     * @Route("/delete/meeting/{id}", name="admin_meeting_delete")
     */
    public function deleteAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();
        $meeting = $em->getRepository('MeetingBundle:Meeting')->findOneById($id);
        $em->remove($meeting);
        $em->flush();
        return $this->redirect($this->generateUrl("admin_meetings"));
    }

}

src/MeetingBundle/Resources/views/Meeting/detailShow.html.twig
{% extends "::base.html.twig" %}
{% block title %}Admin | DetailShow Meeting{% endblock %}
{% block body %}


   <div class="panel panel-info">
       <h2 class="bg-primary" align="right">{{meeting.title}}</h2>
       <img src="{{ meeting.pathFullImg }}" class="img-rounded" width="250px" height="250px" align="left">
       <h3 class="text-info" align="right"> Детальное описание встречи: {{meeting.Description}}</h3>
       <p class="text-info" align="right">Дата создания: {{meeting.created|date("d.m.Y H:i") }}</p>
       <p class="text-info" align="right">Дата проведения: {{meeting.meetingDate|date("d.m.Y H:i") }}</p>
       <p class="text-info" align="right">Место проведения встречи: {{meeting.venue}}</p>
       <p class="text-info" align="right">Количество участвующих:{{ meeting.members|length }} из {{meeting.quantity}}</p>
{% if subscribe %}
    Вы уже подписаны на эту встречу
{% else %}
    {% if app.user and meeting.members|length <= meeting.quantity %}
        <a class="btn btn-info"  href="{{ path('subscribe_meeting',{'id':meeting.id}) }}">Участвовать</a>
    {% else %}
        <a class="btn btn-info" href="{{ path('login') }}">Зарегистрироваться</a>
    {% endif %}
{% endif %}
     </div>
    <hr>

{% endblock %}

src/MeetingBundle/Resources/views/Meeting/edit.html.twig
{% extends "::base.html.twig" %}
{% block title %}Admin | Edit Meeting{% endblock %}
{% block body %}
    <a class="btn btn-info" href="{{ path("admin_meetings") }}">Back</a>

    {% for flashMessage in app.session.flashbag.get('success') %}
        <div class="alert-success alert">
            {{ flashMessage }}
        </div>
    {% endfor %}
    <h2>Edit Meeting</h2>
    <p>Created: {{ meeting.created|date('d.m.Y H:i:s') }}</p>
    <p>Updated: {{ meeting.updated|date('d.m.Y H:i:s') }}</p>
    {{ form_start(form) }}
    <div>
        {{ form_label(form.title) }}
        {{ form_errors(form.title) }}
        {{ form_widget(form.title) }}
    </div>
    <div>
        {{ form_label(form.venue) }}
        {{ form_errors(form.venue) }}
        {{ form_widget(form.venue) }}
    </div>
    <div>

        {{ form_label(form.previewFile) }}
        {{ form_errors(form.previewFile) }}
        <div>
            <img src="{{ meeting.pathPreviewImg }}">
        </div>
        {{ form_widget(form.previewFile) }}
    </div>
    <div>
        {{ form_label(form.fullFile) }}
        {{ form_errors(form.fullFile) }}
        <div>
             <img src="{{ meeting.pathFullImg }}">
        </div>
        {{ form_widget(form.fullFile) }}
    </div>
    <div>
        {{ form_label(form.meetingDate) }}
        {{ form_errors(form.meetingDate) }}
        {{ form_widget(form.meetingDate) }}
    </div>
    <div>
        {{ form_label(form.description) }}
        {{ form_errors(form.description) }}
        {{ form_widget(form.description) }}
    </div>
    <div>
        {{ form_label(form.shortDescription) }}
        {{ form_errors(form.shortDescription) }}
        {{ form_widget(form.shortDescription) }}
    </div>
    <div>
        {{ form_label(form.quantity) }}
        {{ form_errors(form.quantity) }}
        {{ form_widget(form.quantity) }}
    </div>
    {{ form_end(form) }}
{% endblock %}

src/MeetingBundle/Resources/views/Meeting/index.html.twig
{% extends "::base.html.twig" %}
{% block title %}Admin|Meetings{% endblock %}
{% block body %}
<h2>Meetings</h2>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>ID</td>
                <td>Название</td>
                <td>Дата</td>
                <td>Место</td>
                <td>Количество</td>
                <td>Actions</td>
            </tr>
        </thead>
        <tbody>
            {% for m in meetings %}
                <tr>
                    <td><a href="{{ path('admin_meeting_edit', {'id': m.id}) }}">{{ m.id }}</a></td>
                    <td>{{ m.title }}</td>
                    <td>{{ m.meetingDate|date("d.m.Y H:i") }}</td>
                    <td>{{ m.venue }}</td>
                    <td>{{ m.quantity }}</td>
                    <td>
                        <a href="{{ path('admin_meeting_edit', {'id': m.id}) }}">Edit</a> |
                        <a href="{{ path('admin_meeting_delete', {'id': m.id}) }}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
<a class="btn btn-info" href="{{ path("admin_meeting_new") }}">Создать встречу</a>
{% endblock %}

src/MeetingBundle/Resources/views/Meeting/member.html.twig
{% extends "::base.html.twig" %}
{% block title %}Admin |Member{% endblock %}
{% block body %}
    {% for member in meeting.members %}
        <p>{{meeting.members}}</p>
    {% endfor %}
{% endblock %}

src/MeetingBundle/Resources/views/Meeting/new.html.twig
{% extends "::base.html.twig" %}
{% block title %}Admin | New Meeting{% endblock %}
{% block body %}
    <a class="btn btn-info" href="{{ path("admin_meetings") }}">Back</a>

    {% for flashMessage in app.session.flashbag.get('success') %}
        <div class="alert-success alert">
            {{ flashMessage }}
        </div>
    {% endfor %}
    <h2>New Meeting</h2>
    {{ form_start(form) }}
    <div>
        {{ form_label(form.title) }}
        {{ form_errors(form.title) }}
        {{ form_widget(form.title) }}
    </div>
    <div>
        {{ form_label(form.venue) }}
        {{ form_errors(form.venue) }}
        {{ form_widget(form.venue) }}
    </div>
    <div>

        {{ form_label(form.previewFile) }}
        {{ form_errors(form.previewFile) }}
        <div>
            <img src="{{ meeting.pathPreviewImg }}">
        </div>
        {{ form_widget(form.previewFile) }}
    </div>

    <div>
        {{ form_label(form.fullFile) }}
        {{ form_errors(form.fullFile) }}
        <div>
            <img src="{{ meeting.pathFullImg }}">
        </div>
        {{ form_widget(form.fullFile) }}
    </div>

    <div>
        {{ form_label(form.meetingDate) }}
        {{ form_errors(form.meetingDate) }}
        {{ form_widget(form.meetingDate) }}
    </div>
    <div>
        {{ form_label(form.description) }}
        {{ form_errors(form.description) }}
        {{ form_widget(form.description) }}
    </div>
    <div>
        {{ form_label(form.shortDescription) }}
        {{ form_errors(form.shortDescription) }}
        {{ form_widget(form.shortDescription) }}
    </div>
    <div>
        {{ form_label(form.quantity) }}
        {{ form_errors(form.quantity) }}
        {{ form_widget(form.quantity) }}
    </div>
    {{ form_end(form) }}
{% endblock %}

src/MeetingBundle/Resources/views/Meeting/show.html.twig
{% extends "::base.html.twig" %}
{% block title %}Admin | Show Meeting{% endblock %}
{% block body %}

{% for meeting in meetings %}
    <table class="table table-bordered">
   <div class="panel panel-info">
       <img src="{{ meeting.pathPreviewImg }}" width="150px" height="150px" align="left" class="img-circle">
       <h2 class="bg-primary">{{meeting.title}}</h2>
       <p class="text-info">Дата создания: {{meeting.created|date("d.m.Y H:i") }}<p>
       <p class ="text-danger">Дата проведения: {{meeting.meetingDate|date("d.m.Y H:i") }}</p>
       <p class="text-info">Краткое описание встречи: {{meeting.shortDescription}}</p>
       <a class="btn btn-info" href="{{ path('meeting_detail',{'id':meeting.id}) }}">Детальное описание встречи</a>
   </div>
    </table>
    {% endfor %}

   {% endblock %}